#language: go 

arch:
  #- amd64
  #- arm64
  - ppc64le
  #- s390x

dist: xenial

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
#services:
#  - postgresql

script:
  - psql -V
  - dpkg -l | grep postgre
  - ps aux | grep postgre
  
  
