#language: go 
matrix:
  include:
    - env: ENV=bionic
      dist: bionic
      arch: ppc64le
    - env: ENV=xenial
      dist: xenial
      arch: ppc64le
#arch:
  #- amd64
  #- arm64
 # - ppc64le
  #- s390x

#dist: xenial
#dist: bionic

#addons:
#  postgresql: "10"
#  apt:
#    packages:
#    - postgresql-10
#    - postgresql-client-10
services:
  - postgresql

script:
  - psql -V
  - dpkg -l | grep postgre
  - ps aux | grep postgre
  - sudo systemctl status postgresql
  - psql -c 'create database travis_ci_test;' -U postgres
  #- mysql -e 'CREATE DATABASE myapp_test;'
