#language: go 
matrix:
  include:
    - env: ENV=bionic-power-LXD
      dist: bionic
      arch: ppc64le
    - env: ENV=xenial-power-LXD
      dist: xenial
      arch: ppc64le
    - env: ENV=xenial_power-VM
      os: linux-ppc64le

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql

script:
  - psql -V
  # - dpkg -l | grep postgre
  # - ps aux | grep postgre
  #- psql -c 'create database travis_ci_test;' -U postgres
  #- mysql -e 'CREATE DATABASE myapp_test;'
